### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [farnaf/tip-calculator#1]
Thanks for submitting your pre-work, but your current submission is incomplete. Your GIF is not properly rendering or has expired. Please attach a new GIF and we'll check it again. Make sure you've committed all your changes and have pushed to GitHub. Please review the steps for [preparing and pushing your project to GitHub](https://courses.codepath.org/snippets/ios_university/prework.md#heading-4-submitting-the-project).

Please re-submit your project on your [application dashboard](https://apply.codepath.org/dashboard/), and it will notify us to review again.

**Comment by farnaf** [comment]
Sorry about that, should be fixed now!
